### ISSUE TITLE
PNG output test failures w/ libpng@1.6.16

### ISSUE THREAD

**Issue by oncletom** [bbcrd/audiowaveform#20]
Test are ran on OSX.

```
[  FAILED  ] 4 tests, listed below:
[  FAILED  ] OptionHandlerTest.shouldRenderWaveformImageFromBinaryWaveformData
[  FAILED  ] OptionHandlerTest.shouldRenderWaveformImageFromWavAudio
[  FAILED  ] OptionHandlerTest.shouldRenderWaveformImageFromMp3Audio
[  FAILED  ] OptionHandlerTest.shouldRenderWaveformImageFromFlacAudio
```

```
[ RUN      ] OptionHandlerTest.shouldRenderWaveformImageFromBinaryWaveformData
/Users/thomaspa/Projects/audiowaveform/test/OptionHandlerTest.cpp:67: Failure
Value of: a.size()
Expected: is equal to 4954
  Actual: 4975 (of type unsigned long)
[  FAILED  ] OptionHandlerTest.shouldRenderWaveformImageFromBinaryWaveformData (12 ms)
[ RUN      ] OptionHandlerTest.shouldRenderWaveformImageFromWavAudio
/Users/thomaspa/Projects/audiowaveform/test/OptionHandlerTest.cpp:67: Failure
Value of: a.size()
Expected: is equal to 4980
  Actual: 5001 (of type unsigned long)
[  FAILED  ] OptionHandlerTest.shouldRenderWaveformImageFromWavAudio (14 ms)
[ RUN      ] OptionHandlerTest.shouldRenderWaveformImageFromMp3Audio
/Users/thomaspa/Projects/audiowaveform/test/OptionHandlerTest.cpp:67: Failure
Value of: a.size()
Expected: is equal to 4980
  Actual: 5001 (of type unsigned long)
[  FAILED  ] OptionHandlerTest.shouldRenderWaveformImageFromMp3Audio (21 ms)
[ RUN      ] OptionHandlerTest.shouldRenderWaveformImageFromFlacAudio
/Users/thomaspa/Projects/audiowaveform/test/OptionHandlerTest.cpp:67: Failure
Value of: a.size()
Expected: is equal to 4980
  Actual: 5001 (of type unsigned long)
[  FAILED  ] OptionHandlerTest.shouldRenderWaveformImageFromFlacAudio (17 ms)
```

Let me know if you need additional details about CPU/architecture/etc.

**Comment by chrisn** [comment]
Hi Thomas,

These tests compare the output from audiowaveform against precomputed PNG image files. The tests now fail because you're using a newer version of libpng (via libgd) that generates PNG files that, although visibly the same, are different length So, the problem is with the tests rather than the application code.

Chris

**Comment by oncletom** [comment]
Ah yes… I guess for now it is not an issue. But it might happen in the future on Ubuntu right?

Is there any documentation describing how to generate the set of image references used in the test suite?

**Comment by chrisn** [comment]
This problem also occurs with Ubuntu 14.04. You can see the options used to generate the reference images in the test code [here](https://github.com/bbcrd/audiowaveform/blob/master/test/OptionHandlerTest.cpp#L281).

To fix this, I'm thinking of rewriting the tests to perform a more intelliigent comparison against the reference images rather than the simple binary diff I use at the moment.

**Comment by oncletom** [comment]
@chrisn tests now pass, good job :-)
