### ISSUE TITLE
.dat to json not working correctly

### ISSUE THREAD

**Issue by v1r** [bbcrd/audiowaveform#24]
audiowaveform -i  test.dat -o test.json -w 700 -h 500
Reading waveform data file: test.dat
Sample rate: 16000 Hz
Bits: 8
Samples per pixel: 256
Length: 487829 points
Writing output file: test.json

I tried all options -s -e --pixels-per-seconds the returned data is always the same...  it works well with image generation. 
Is this a bug or I am not doing it right! 
Btw. this an awesome library!!

**Comment by v1r** [comment]
I get it now, the json file is only a conversion of the .dat..

**Comment by chrisn** [comment]
Hi Karim,

As you've found, the `-w`, `-h`, `-s`, and `-e` options (width, height, start, and end) are only used when generating PNG images.

The JSON output format is really only intended for use with the [Peaks.js](https://github.com/bbcrd/peaks.js/) library. When converting .dat format to .json, audiowaveform simply converts the entire waveform data file, and these options have no effect. Possibly the program should report an error rather than just ignore the options though.

Chris

**Comment by v1r** [comment]
Thanks chrisn for you answer.. It would be a good feature to add. I think the logic behind it is the same as drawing the png file.
